### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by barscn** [MehmetSemerci/MembApp#1]
There is a problem with member_support.py which tries to import tkinter messagebox module but it fails in linux. I think it is because of the python version. 

`Traceback (most recent call last):
  File "linux.py", line 21, in <module>
    import member_support
  File "/home/bariscan/Downloads/MembApp-master/member_support.py", line 24, in <module>
    from tkinter import messagebox
ImportError: No module named tkinter`

**Comment by MehmetSemerci** [comment]
Which python version you are using?

**Comment by barscn** [comment]
I have both 2.x and 3.x. They give same error
